### ISSUE TITLE
Zoom as computed property causes stack overflow

### ISSUE THREAD

**Issue by pinx** [Matt-Jensen/ember-cli-g-maps#34]
In the controller, we have
  zoom: Ember.computed('model.radius', {
    get(key) {
      let radius = this.get('model.radius');
      return Math.round(14-Math.log(radius)/Math.LN2);
    },
    set(key, value) {
    }
  }),

We should follow the DDAU pattern.

**Comment by Matt-Jensen** [comment]
@pinx first of all thanks for reporting this.  Completely agree that the the g-maps component needs to do a better job of supporting computed properties.

So the stack overflow issue, as far as I could determine, was due to the computed property producing an occasional non-number value. For example set() is returning "undefined". I will need to account for this of course, but in the mean time you will have to ensure the zoom computed property is always producing a typeof === number.

My issue with solving this with DDAU is that like 98% of the time when a user interacts with a map you're going to want that input to persist to your model.  Requiring a ember-cli-g-maps users to recreate this glue code every single time, for every single map, seems like no smiles times.

If you would like to reserve the ability to update the underlying model outside of ember-cli-g-maps, I would argue this should be an, off the happy path, option this project supports via computed properties' set method. We could solve this with some documentation around implementing computed properties like so: https://gist.github.com/Matt-Jensen/7419236e9425ecbe593c

Any thoughts?

**Comment by Matt-Jensen** [comment]
Stack overflow issue fixed
