### ISSUE TITLE
Multiple markers possible?

### ISSUE THREAD

**Issue by stijn26** [Matt-Jensen/ember-cli-g-maps#43]
Hi,

Is it possible to add multiple dynamically generated markers to a Google Map.
Like this (in ember-g-map addon):
```
{{#each markers as |marker|}}
    {{g-map-marker context lat=hotspot.lat lng=hotspot.lng }}
{{/each}}
```

The problem with the ember-g-map addon is that the markers aren't draggable.

**Comment by Matt-Jensen** [comment]
Great question.  We're currently working out a good way to implement this with either: contextual components or components with positional params (such as you have detailed).  However, since this is a design decision that, I believe, should promote/facilitate a community of Google Map addons that extend this project's functionality I want to be sure the correct decision is made.  There's currently a lot of repeated effort in the Ember CLI map addon space simply because no one is providing sane extendibility.

However, if it is any help to you, multiple markers are possible by:
``{{g-maps markers=myMarkersArray}}``
[Markers documentation](http://matt-jensen.github.io/ember-cli-g-maps/#/basic-usage/markers)

**Comment by stijn26** [comment]
Oke thank you. Great work nonetheless and thank you for this addon.

**Comment by Matt-Jensen** [comment]
grazie
